import { sql } from "drizzle-orm";
import { integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = {
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
};

export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull().unique(), role: text("role", { enum: ["user", "admin"] }).notNull().default("user"), verifiedAt: text("verified_at"), ...timestamps });
export const businesses = sqliteTable("business_profiles", { id: text("id").primaryKey(), ownerId: text("owner_id").notNull().references(() => users.id), name: text("name").notNull(), ownerName: text("owner_name").notNull(), phone: text("phone").notNull(), registrationNo: text("registration_no"), address: text("address"), currency: text("currency").notNull().default("MYR"), timezone: text("timezone").notNull().default("Asia/Kuala_Lumpur"), language: text("language").notNull().default("en"), quotationValidityDays: integer("quotation_validity_days").notNull().default(14), paymentTerms: text("payment_terms").notNull().default("Payment due on completion"), ...timestamps }, t => [uniqueIndex("idx_business_owner").on(t.ownerId)]);
export const customers = sqliteTable("customers", { id: text("id").primaryKey(), accountId: text("account_id").notNull().references(() => businesses.id), name: text("name").notNull(), phone: text("phone").notNull(), whatsapp: text("whatsapp"), email: text("email"), serviceAddress: text("service_address").notNull(), notes: text("notes"), tagsJson: text("tags_json").notNull().default("[]"), deletedAt: text("deleted_at"), ...timestamps });
export const jobs = sqliteTable("jobs", { id: text("id").primaryKey(), accountId: text("account_id").notNull().references(() => businesses.id), customerId: text("customer_id").notNull().references(() => customers.id), jobNumber: text("job_number").notNull(), category: text("category").notNull(), serviceAddress: text("service_address").notNull(), request: text("request").notNull(), appointmentAt: text("appointment_at"), technician: text("technician"), internalNotes: text("internal_notes"), followUpAt: text("follow_up_at"), status: text("status", { enum: ["new", "quoted", "confirmed", "in_progress", "completed", "cancelled"] }).notNull().default("new"), ...timestamps }, t => [uniqueIndex("idx_jobs_account_number").on(t.accountId, t.jobNumber)]);
export const reminders = sqliteTable("reminders", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), customerId: text("customer_id"), jobId: text("job_id"), type: text("type").notNull(), dueAt: text("due_at").notNull(), note: text("note"), completedAt: text("completed_at"), ...timestamps });
export const documents = sqliteTable("documents", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), customerId: text("customer_id").notNull(), jobId: text("job_id"), kind: text("kind", { enum: ["quotation", "work_report", "invoice"] }).notNull(), documentNumber: text("document_number").notNull(), status: text("status", { enum: ["draft", "confirmed", "void"] }).notNull().default("draft"), currency: text("currency").notNull().default("MYR"), subtotalMinor: integer("subtotal_minor").notNull().default(0), taxMinor: integer("tax_minor").notNull().default(0), totalMinor: integer("total_minor").notNull().default(0), confirmedAt: text("confirmed_at"), ...timestamps }, t => [uniqueIndex("idx_documents_account_number").on(t.accountId, t.documentNumber)]);
export const documentVersions = sqliteTable("document_versions", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), documentId: text("document_id").notNull().references(() => documents.id), version: integer("version").notNull(), contentJson: text("content_json").notNull(), source: text("source", { enum: ["manual", "ai"] }).notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t => [uniqueIndex("idx_document_version").on(t.documentId, t.version)]);
export const quotationItems = sqliteTable("quotation_items", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), documentId: text("document_id").notNull(), description: text("description").notNull(), quantityMilli: integer("quantity_milli").notNull(), unit: text("unit").notNull(), unitPriceMinor: integer("unit_price_minor").notNull(), amountMinor: integer("amount_minor").notNull(), sortOrder: integer("sort_order").notNull() });
export const completionReports = sqliteTable("completion_reports", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), documentId: text("document_id").notNull().unique(), serviceDate: text("service_date").notNull(), findings: text("findings").notNull(), workPerformed: text("work_performed").notNull(), testingResults: text("testing_results"), warranty: text("warranty"), recommendations: text("recommendations"), technician: text("technician").notNull() });
export const invoiceItems = sqliteTable("invoice_items", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), documentId: text("document_id").notNull(), description: text("description").notNull(), quantityMilli: integer("quantity_milli").notNull(), unitPriceMinor: integer("unit_price_minor").notNull(), amountMinor: integer("amount_minor").notNull(), sortOrder: integer("sort_order").notNull() });
export const attachments = sqliteTable("attachments", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), jobId: text("job_id"), documentId: text("document_id"), storageKey: text("storage_key").notNull().unique(), fileName: text("file_name").notNull(), mimeType: text("mime_type").notNull(), sizeBytes: integer("size_bytes").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const aiAnalyses = sqliteTable("ai_analyses", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), generationId: text("generation_id").notNull(), resultJson: text("result_json").notNull(), verifiedAt: text("verified_at"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const generationEvents = sqliteTable("generation_events", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), intent: text("intent").notNull(), provider: text("provider").notNull(), model: text("model").notNull(), status: text("status", { enum: ["reserved", "succeeded", "failed", "reversed"] }).notNull(), durationMs: integer("duration_ms"), costMicros: integer("cost_micros"), idempotencyKey: text("idempotency_key").notNull().unique(), errorCode: text("error_code"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const plans = sqliteTable("plans", { id: text("id").primaryKey(), code: text("code").notNull().unique(), name: text("name").notNull(), monthlyPriceMinor: integer("monthly_price_minor").notNull(), annualPriceMinor: integer("annual_price_minor").notNull(), monthlyCredits: integer("monthly_credits").notNull(), configJson: text("config_json").notNull(), active: integer("active", { mode: "boolean" }).notNull().default(true), ...timestamps });
export const subscriptions = sqliteTable("subscriptions", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), planId: text("plan_id").notNull(), provider: text("provider").notNull(), providerSubscriptionId: text("provider_subscription_id").unique(), status: text("status").notNull(), periodStart: text("period_start").notNull(), periodEnd: text("period_end").notNull(), cancelAtPeriodEnd: integer("cancel_at_period_end", { mode: "boolean" }).notNull().default(false), ...timestamps });
export const payments = sqliteTable("payments", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), provider: text("provider").notNull(), providerPaymentId: text("provider_payment_id").unique(), kind: text("kind", { enum: ["subscription", "credit_bundle"] }).notNull(), status: text("status").notNull(), amountMinor: integer("amount_minor").notNull(), currency: text("currency").notNull().default("MYR"), feeMinor: integer("fee_minor"), idempotencyKey: text("idempotency_key").notNull().unique(), ...timestamps });
export const creditLedger = sqliteTable("credit_ledger_entries", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), eventType: text("event_type").notNull(), amount: integer("amount").notNull(), source: text("source", { enum: ["welcome", "subscription", "top_up", "adjustment"] }).notNull(), paymentId: text("payment_id"), subscriptionId: text("subscription_id"), generationId: text("generation_id"), idempotencyKey: text("idempotency_key").notNull().unique(), actorId: text("actor_id").notNull(), adminReason: text("admin_reason"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const adminAuditLogs = sqliteTable("admin_audit_logs", { id: text("id").primaryKey(), adminId: text("admin_id").notNull(), accountId: text("account_id"), action: text("action").notNull(), reason: text("reason").notNull(), metadataJson: text("metadata_json").notNull().default("{}"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
